from . import about_me
from . import achievements
from . import contact
from . import home
from . import my_skill
from . import my_work
from . import service
from . import contact_info
from . import testimonial
