# Generated by Django 4.2 on 2023-04-14 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_aboutme_created_at_alter_aboutme_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='pic',
            field=models.ImageField(default=datetime.datetime(2023, 4, 14, 18, 40, 52, 254820, tzinfo=datetime.timezone.utc), upload_to='media/images/'),
            preserve_default=False,
        ),
    ]
