# Generated by Django 4.2 on 2023-04-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_aboutme_pic_alter_mywork_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='pic',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
